description:
  fin: |
    <p><strong>Korp</strong> on <a href="https://www.kielipankki.fi"
    target="_blank">Kielipankin</a> sanatutkimusalusta.</p>
    <p>
      Korpissa voi hakea suurista tekstiaineistoista, jotka sisältävät
      mm. sanomalehtiä, uutistekstejä, verkkokeskusteluja ja
      murreaineistoja.
      Näihin tekstikokoelmiin, <em>korpuksiin</em>, on annotoitu
      kielellisiä ja muita piirteitä.
      Katso lisätietoja
      <a href="https://www.kielipankki.fi/tuki/korp/" target="_blank">Korpin käyttöohjeista</a>.
    </p>
    <p>
      Jos käytät Korpia työssäsi,
      <a href="https://spraakbanken.gu.se/en/about/howtocite#Korp" target="_blank">viittaa siihen</a>.
      (Korp-ohjelmisto on kehitetty Göteborgin yliopiston Språkbanken
      Textissä.)
      Jos sinulla on kysymyksiä tai kommentteja, ota yhteyttä: <a href="mailto:fin-clarin@helsinki.fi" class="whitespace-nowrap">fin-clarin (ät) helsinki.fi</a>
    </p>
  eng: |
    <p><strong>Korp</strong> is the word research platform in <a
    href="https://www.kielipankki.fi/language-bank/"
    target="_blank">Kielipankki (the Language Bank of
    Finland)</a>.</p>
    <p>
      Search in large amounts of texts, including newspapers,
      internet discussion forums and dialect resources.
      The text collections, <em>corpora</em>, are annotated for
      linguistic features and other attributes.
      Please refer to the
      <a href="https://www.kielipankki.fi/support/korp/" target="_blank">Korp user guide</a>
      for more information.
    </p>
    <p>
      If you are using Korp in your work, please
      <a href="https://spraakbanken.gu.se/en/about/howtocite#Korp" target="_blank">cite it</a>.
      (The Korp software has been developed in Språkbanken Text at the
      University of Gothenburg.)
      For questions or comments, contact us at
      <a href="mailto:fin-clarin@helsinki.fi" class="whitespace-nowrap">fin-clarin (at) helsinki.fi</a>.
    </p>
  swe: |
    <p><strong>Korp</strong> är ordforskningsplattform i <a
    href="https://www.kielipankki.fi/sprakbanken/"
    target="_blank">Kielipankki (Språkbanken i Finland)</a>.</p>
    <p>
      Här kan du söka i stora mängder text från bland annat
      dagstidningar, diskussionsforum och dialektmaterial.
      Textsamlingarna, <em>korpusarna</em>, är annoterade med
      språkliga och andra attribut.
      Se gärna <a href="https://www.kielipankki.fi/support/korp/" target="_blank">Användarhandledningen</a>
      för mer information (på englelska).
    </p>
    <p>
      Om du använder Korp i ditt arbete ber vi dig
      <a href="https://spraakbanken.gu.se/om/referera#Korp">referera till Korp</a>.
      För frågor och kommentarer, kontakta
      <a href="mailto:fin-clarin@helsinki.fi" class="whitespace-nowrap">fin-clarin (at) helsinki.fi</a>.
    </p>

logo:
  korp: |
    <img src="img/korp.svg" height="300" width="300" />
  organization: |
    <a
        class="hidden min-[1150px]:flex h-20 shrink flex-col justify-end"
        href="https://www.kielipankki.fi/"
        target="_blank"
    >
        <img src="img/Kielipankki-logo-korp-2.png"
             style="height: 100px; margin-bottom: 2px; margin-right: 10px;" />
    </a>
  chooser_right: |
    <img src="img/Possu-korp.png" style="margin: 4px;" />

auth_module:
  module: "federated_auth"
  options:
    jwt_url: "https://www.kielipankki.fi/future/mink/auth/jwt"
    login_service: "https://www.kielipankki.fi/future/mink/auth/login"
    logout_service: "https://www.kielipankki.fi/future/mink/auth/logout"
  # module: "basic_auth"
  # options:
  #   default_value_remember: true


autocomplete: true
map_enabled: true
hits_per_page_values:
  - 25
  - 50
  - 75
  - 100
  - 500
  - 1000

# corpus_info_link:
#   url_template:
#     swe: https://spraakbanken.gu.se/resurser/%s
#     eng: https://spraakbanken.gu.se/en/resources/%s
#   label:
#     swe: Mer information
#     eng: More information

enable_backend_kwic_download: false
enable_frontend_kwic_download: true

default_language: fin
languages:
  - value: fin
    label: Suomi
  - value: swe
    label: Svenska
  - value: eng
    label: English

frontpage:
  corpus_updates: true

word_label:
  fin: sana
  swe: ord
  eng: word

group_statistics:
  - saldo
  - prefix
  - suffix
  - lex
  - lemma
  - sense
  - text_swefn
  - text_blingbring
  - word-prediction--kb-bert
  - e_cat

statistics_search_default: false

# for 'compile statistics by' selector, can be 'union' or 'intersection'
reduce_word_attribute_selector: intersection
reduce_struct_attribute_selector: intersection

# matomo:
#   url: https://spraakbanken.gu.se/stats/
#   # Enable real reporting only on live sites
#   staging:
#     site: 3
#   production:
#     site: 3

news_url: https://raw.githubusercontent.com/CSCfi/Kielipankki-korp-frontend/news/future/data/korp.yaml

word_picture_tagset:
    # supported pos-tags
    verb: vb
    noun: nn
    adjective: jj
    adverb: ab
    preposition: pp

    # dependency releations
    subject: ss
    object: obj
    adverbial: adv
    preposition_rel: pa
    pre_modifier: at
    post_modifier: et
    adverbial2: aa

word_picture_conf:
  verb:
    - - rel: subject
        css_class: color_blue
      - _
      - rel: object
        css_class: color_purple
      - rel: adverbial
        css_class: color_green
  noun:
    - - rel: preposition_rel
        css_class: color_yellow
        field_reverse: true
      - rel: pre_modifier
        css_class: color_azure
      - _
      - rel: post_modifier
        css_class: color_red
    - - _
      - rel: subject
        css_class: color_blue
        field_reverse: true
        alt_label: vb
    - - rel: object
        css_class: color_purple
        field_reverse: true
        alt_label: vb
      - _
  adjective:
    - - _
      - rel: pre_modifier
        css_class: color_yellow
        field_reverse: true
    - - rel: adverbial2
        css_class: color_purple
      - _
  adverb:
    - - _
      - rel: adverbial
        css_class: color_yellow
        field_reverse: true
    - - _
      - rel: adverbial2
        css_class: color_purple
        field_reverse: true
  preposition:
    - - _
      - rel: preposition_rel
        css_class: color_green

default_overview_context: 1 sentence
default_reading_context: 1 paragraph

default_within:
  sentence: sentence

default_options:
  is: =
  is_not: '!='
  starts_with: ^=
  contains: _=
  ends_with: '&='
  matches: '*='
  matches_not: '!*='

korp_backend_url: "https://www.kielipankki.fi/future/korp/api8/"

map_center:
  lat: 64.180708
  lng: 25.803222
  zoom: 4

common_struct_types:
  date_interval:
    label: 
      eng: time interval
      fin: aikaväli
      swe: tidsintervall
    hide_sidebar: 'true'
    hide_compare: 'true'
    hide_statistics: 'true'
    opts: false
    extended_component: dateInterval
